import { Inter } from "next/font/google";
import "./globals.css";
import SessionProvider from "@/components/session-provider";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      suppressHydrationWarning={true}
      lang="en"
    >
      <body className={inter.className}>{children}
      <SessionProvider />
      <Toaster />
      </body>
    </html>
  );
}
