export const listSpace = [
  {
    name: "Nature",
    data: [
      "https://www.youtube.com/embed/mCXS1Oxi9lY",
      "https://www.youtube.com/embed/3w1mZQnTVL8",
      "https://www.youtube.com/embed/fW-mixqTTwE",
      "https://www.youtube.com/embed/Nq1AdAYMgt0",
      "https://www.youtube.com/embed/Fm0sToWtatw",
    ],
    img: "https://pub-aceabaa1ff6f48f7872c8684996a45ee.r2.dev/mountain_26f0-fe0f.png",
  },
  {
    name: "Snow",
    data: [
      "https://www.youtube.com/embed/Fm0sToWtatw",
      "https://www.youtube.com/embed/nrVLUXU1kpM",
      "https://www.youtube.com/embed/FslCeCp1GqM",
      "https://www.youtube.com/embed/drGZvqvBzV4",
      "https://www.youtube.com/embed/mWNkRN1lzOk",
    ],
    img: "https://em-content.zobj.net/source/apple/354/snowman-without-snow_26c4.png",
  },
  {
    name: "City",
    data: [
      "https://www.youtube.com/embed/Ho7a8rpufHg",
      "https://www.youtube.com/embed/0FbI-V12KKI",
      "https://www.youtube.com/embed/_btcrl9jg3I",
      "https://www.youtube.com/embed/hBGbt2CRDpA",
      "https://www.youtube.com/embed/oR9VY94f7bc",
    ],
    img: "https://pub-aceabaa1ff6f48f7872c8684996a45ee.r2.dev/cityscape_1f3d9-fe0f.png",
  },
  {
    name: "Commute",
    data: [
      "https://www.youtube.com/embed/cZGZVY2REXA",
      "https://www.youtube.com/embed/WKFMKV05OVU",
      "https://www.youtube.com/embed/AO1OoQ-P5QY",
      "https://www.youtube.com/embed/F7_BwCS6r5M",
      "https://www.youtube.com/embed/jJTmuTpsv1s",
    ],
    img: "https://pub-aceabaa1ff6f48f7872c8684996a45ee.r2.dev/bullet-train_1f685.png",
  },
  {
    name: "Art",
    data: [
      "https://www.youtube.com/embed/vmfNQFCnlJE",
      "https://www.youtube.com/embed/pX5HL3fO-hQ",
    ],
    img: "https://pub-aceabaa1ff6f48f7872c8684996a45ee.r2.dev/artist-palette_1f3a8.png",
  },
  {
    name: "Space",
    data: [
      "https://www.youtube.com/embed/ZEPQDxEXRBU",
      "https://www.youtube.com/embed/TLP1BgTDFKE",
      "https://www.youtube.com/embed/CMW4-hzFPrI",
      "https://www.youtube.com/embed/kBZJhKDhu60",
      "https://www.youtube.com/embed/Iv368LFjG7U",
      "https://www.youtube.com/embed/dOdTRC50hfs",
      "https://www.youtube.com/embed/8vOZYwsm8X0",
    ],
    img: "https://pub-aceabaa1ff6f48f7872c8684996a45ee.r2.dev/ringed-planet_1fa90.png",
  },
  {
    name: "K-pop",
    data: [
      "https://www.youtube.com/embed/I-aE2ShpAuA",
      "https://www.youtube.com/embed/oadMhHMubQ4",
      "https://www.youtube.com/embed/mHGF5VlS7fw",
      "https://www.youtube.com/embed/vRfNw33kMlE",
    ],
    img: "https://pub-aceabaa1ff6f48f7872c8684996a45ee.r2.dev/admission-tickets_1f39f-fe0f.png",
  },
  {
    name: "Games",
    data: [
      "https://www.youtube.com/embed/cL0AHxwMt2I",
      "https://www.youtube.com/embed/4yf95SnAMr8",
      "https://www.youtube.com/embed/iYMdmxgZZk0",
      "https://www.youtube.com/embed/-jI_sA-Dt_U",
      "https://www.youtube.com/embed/IraBA3Nz-9o",
    ],
    img: "https://pub-aceabaa1ff6f48f7872c8684996a45ee.r2.dev/joystick_1f579-fe0f.png",
  },
  {
    name: "Library",
    data: [
      "https://www.youtube.com/embed/h414quf-mmE",
      "https://www.youtube.com/embed/-VgN7nKx9MU",
      "https://www.youtube.com/embed/ZiGaydG91zI",
      "https://www.youtube.com/embed/3-rVjesZDbg",
    ],
    img: "https://pub-aceabaa1ff6f48f7872c8684996a45ee.r2.dev/books_1f4da.png",
  },
  {
    name: "Fantasy",
    data: [
      "https://www.youtube.com/embed/30b7_S0paCQ",
      "https://www.youtube.com/embed/jATVgJ_grys",
      "https://www.youtube.com/embed/wFrIeXGXEco",
      "https://www.youtube.com/embed/t4x81hvDLA8",
      "https://www.youtube.com/embed/acsLxmnjMho",
    ],
    img: "https://pub-aceabaa1ff6f48f7872c8684996a45ee.r2.dev/owl_1f989.png",
  },
  {
    name: "Mystery",
    data: [
      "https://www.youtube.com/embed/Pbzn79TSRO0",
      "https://www.youtube.com/embed/U2gNsLiki_I",
      "https://www.youtube.com/embed/PLRCWgjFIwg",
      "https://www.youtube.com/embed/oA0Ay7xX4-k",
      "https://www.youtube.com/embed/3PZ65s2qLTE",
    ],
    img: "https://pub-aceabaa1ff6f48f7872c8684996a45ee.r2.dev/shushing-face_1f92b.png",
  },
  {
    name: "Window",
    data: [
      "https://www.youtube.com/embed/SnHIS_Aqu9o",
      "https://www.youtube.com/embed/vUNWL4sOrd0",
      "https://www.youtube.com/embed/3HuTSbvyqg0",
      "https://www.youtube.com/embed/LO8P2NppjqU",
      "https://www.youtube.com/embed/2jcV7i114BQ",
      "https://www.youtube.com/embed/eJMIokGLsL8",
      "https://www.youtube.com/embed/ZYaF0zLfijg",
      "https://www.youtube.com/embed/WqHU2UBzQSo",
    ],
    img: "https://pub-aceabaa1ff6f48f7872c8684996a45ee.r2.dev/window_1fa9f.png",
  },
  {
    name: "Beach",
    data: [
      "https://www.youtube.com/embed/xGRjCa49C6U",
      "https://www.youtube.com/embed/nO3oGPnur2Y",
      "https://www.youtube.com/embed/A2_yg19Pu7Y",
      "https://www.youtube.com/embed/GgcJmRIGspE",
    ],
    img: "https://pub-aceabaa1ff6f48f7872c8684996a45ee.r2.dev/beach-with-umbrella_1f3d6-fe0f.png",
  },
  {
    name: "Cafe",
    data: [
      "https://www.youtube.com/embed/KLLVXw335u4",
      "https://www.youtube.com/embed/UvV-dK6Nyj8",
      "https://www.youtube.com/embed/nQQWVp9Ud9U",
      "https://www.youtube.com/embed/8yR9y8HFSSI",
    ],
    img: "https://pub-aceabaa1ff6f48f7872c8684996a45ee.r2.dev/hot-beverage_2615.png",
  },
  {
    name: "Pets",
    data: [
      "https://www.youtube.com/embed/QhLMlA3Wb8w",
      "https://www.youtube.com/embed/_ygU_fEZ1-s",
    ],
    img: "https://pub-aceabaa1ff6f48f7872c8684996a45ee.r2.dev/dog_1f415.png",
  },
  {
    name: "Work with me",
    data: [
      "https://www.youtube.com/embed/tBulYcyAL7o",
      "https://www.youtube.com/embed/jHjHu5LOyAk",
      "https://www.youtube.com/embed/2KGtXzIb8l8",
      "https://www.youtube.com/embed/gvqhjyjiguM",
      "https://www.youtube.com/embed/mSrfFsgtoG4",
      "https://www.youtube.com/embed/jQotbjxQfXE",
      "https://www.youtube.com/embed/LG9D9UtaDYw",
      "https://www.youtube.com/embed/xeoBiwa1hwQ",
    ],
    img: "https://pub-aceabaa1ff6f48f7872c8684996a45ee.r2.dev/woman-technologist_1f469-200d-1f4bb.png",
  },
  {
    name: "Code with me",
    data: [
      "https://www.youtube.com/embed/q-WW2Dvw908",
      "https://youtu.be/0GYpj4DNDEc?si=jEn7Bdn0DyWhDCDN",
      "https://youtu.be/v9XyIGXcRck?si=N0q3U0btBMU6_Z2Q",
    ],
    img: "https://pub-aceabaa1ff6f48f7872c8684996a45ee.r2.dev/laptop_1f4bb.png",
  },
  {
    name: "Anime",
    data: [
      "https://www.youtube.com/embed/Dh0jhjs2z7c",
      "https://www.youtube.com/embed/etqF_tgh-eU",
      "https://www.youtube.com/embed/KTRRp9N7BTc",
      "https://www.youtube.com/embed/z9Ug-3qhrwY",
      "https://www.youtube.com/embed/RQ7UmN7bVX4",
      "https://www.youtube.com/embed/72-yPWnogWk",
    ],
    img: "https://pub-aceabaa1ff6f48f7872c8684996a45ee.r2.dev/brain_1f9e0.png",
  },
  {
    name: "Walk",
    data: [
      "https://www.youtube.com/embed/5582guhPw0Q",
      "https://www.youtube.com/embed/uZEnkpFXd9I",
    ],
    img: "https://pub-aceabaa1ff6f48f7872c8684996a45ee.r2.dev/person-walking_1f6b6.png",
  },
  {
    name: "Lofi",
    data: [
      "https://www.youtube.com/embed/P8sYrpKI53I",
      "https://www.youtube.com/embed/psJLqTFjcs0",
      "https://www.youtube.com/embed/TGan48YE9Us",
      "https://www.youtube.com/embed/9FvvbVI5rYA",
      "https://www.youtube.com/embed/uUIMrGGM968",
      "https://www.youtube.com/embed/4Ta1a5VAYLg",
      "https://www.youtube.com/embed/56FcUHbxSZg",
      "https://www.youtube.com/embed/wePMdTNW3C4",
      "https://www.youtube.com/embed/7vy43fgW8r0",
      "https://www.youtube.com/embed/Xt6MGW0lVcs",
      "https://www.youtube.com/embed/_TEKpPLnxnc",
      "https://www.youtube.com/embed/Rs-eeohNshs",
      "https://www.youtube.com/embed/RtWgbht6qe8",
      "https://www.youtube.com/embed/pvGV6sI6LHA",
      "https://www.youtube.com/embed/81WBzpwK1Rk",
      "https://www.youtube.com/embed/ALja3wAdQsM",
      "https://www.youtube.com/embed/rwionZbOryo",
      "https://www.youtube.com/embed/9j_7IgS-2G8",
      "https://www.youtube.com/embed/saK3GjC55aM",
      "https://www.youtube.com/embed/u6rMyQwrzfo",
      "https://www.youtube.com/embed/SPYBHFPvvXk",
      "https://www.youtube.com/embed/70uFJGIoJ3E",
    ],
    img: "https://pub-aceabaa1ff6f48f7872c8684996a45ee.r2.dev/crystal-ball_1f52e.png",
  },
  {
    name: "Iiktok",
    data: [
     "https://www.youtube.com/embed/XliMyMdQzd0?si=54hNHzrOlthPgkKZ",
     "https://www.youtube.com/embed/EtxwbVu2bIc?si=acDq1zkWqSjI0XQ-",
     "https://www.youtube.com/embed/Gg69NENaEr8?si=xEp9A7OUjTvqlQwi"
    ],
    img: "https://w7.pngwing.com/pngs/319/597/png-transparent-tiktok-social-media-logos-brands-icon.png",
  },
];

export const listShare = {
  100: "https://www.youtube.com/embed/mCXS1Oxi9lY",
  101: "https://www.youtube.com/embed/3w1mZQnTVL8",
  102: "https://www.youtube.com/embed/fW-mixqTTwE",
  103: "https://www.youtube.com/embed/Nq1AdAYMgt0",
  104: "https://www.youtube.com/embed/Fm0sToWtatw",
  105: "https://www.youtube.com/embed/Fm0sToWtatw",
  106: "https://www.youtube.com/embed/nrVLUXU1kpM",
  107: "https://www.youtube.com/embed/FslCeCp1GqM",
  108: "https://www.youtube.com/embed/drGZvqvBzV4",
  109: "https://www.youtube.com/embed/mWNkRN1lzOk",
  110: "https://www.youtube.com/embed/Ho7a8rpufHg",
  111: "https://www.youtube.com/embed/0FbI-V12KKI",
  112: "https://www.youtube.com/embed/_btcrl9jg3I",
  113: "https://www.youtube.com/embed/hBGbt2CRDpA",
  114: "https://www.youtube.com/embed/oR9VY94f7bc",
  115: "https://www.youtube.com/embed/cZGZVY2REXA",
  116: "https://www.youtube.com/embed/WKFMKV05OVU",
  117: "https://www.youtube.com/embed/AO1OoQ-P5QY",
  118: "https://www.youtube.com/embed/F7_BwCS6r5M",
  119: "https://www.youtube.com/embed/jJTmuTpsv1s",
  120: "https://www.youtube.com/embed/vmfNQFCnlJE",
  121: "https://www.youtube.com/embed/pX5HL3fO-hQ",
  122: "https://www.youtube.com/embed/ZEPQDxEXRBU",
  123: "https://www.youtube.com/embed/TLP1BgTDFKE",
  124: "https://www.youtube.com/embed/CMW4-hzFPrI",
  125: "https://www.youtube.com/embed/kBZJhKDhu60",
  126: "https://www.youtube.com/embed/Iv368LFjG7U",
  127: "https://www.youtube.com/embed/dOdTRC50hfs",
  128: "https://www.youtube.com/embed/8vOZYwsm8X0",
  129: "https://www.youtube.com/embed/I-aE2ShpAuA",
  130: "https://www.youtube.com/embed/oadMhHMubQ4",
  131: "https://www.youtube.com/embed/mHGF5VlS7fw",
  132: "https://www.youtube.com/embed/vRfNw33kMlE",
  133: "https://www.youtube.com/embed/cL0AHxwMt2I",
  134: "https://www.youtube.com/embed/4yf95SnAMr8",
  135: "https://www.youtube.com/embed/iYMdmxgZZk0",
  136: "https://www.youtube.com/embed/-jI_sA-Dt_U",
  137: "https://www.youtube.com/embed/IraBA3Nz-9o",
  138: "https://www.youtube.com/embed/h414quf-mmE",
  139: "https://www.youtube.com/embed/-VgN7nKx9MU",
  140: "https://www.youtube.com/embed/ZiGaydG91zI",
  141: "https://www.youtube.com/embed/3-rVjesZDbg",
  142: "https://www.youtube.com/embed/30b7_S0paCQ",
  143: "https://www.youtube.com/embed/jATVgJ_grys",
  144: "https://www.youtube.com/embed/wFrIeXGXEco",
  145: "https://www.youtube.com/embed/t4x81hvDLA8",
  146: "https://www.youtube.com/embed/acsLxmnjMho",
  147: "https://www.youtube.com/embed/Pbzn79TSRO0",
  148: "https://www.youtube.com/embed/U2gNsLiki_I",
  149: "https://www.youtube.com/embed/PLRCWgjFIwg",
  150: "https://www.youtube.com/embed/oA0Ay7xX4-k",
  151: "https://www.youtube.com/embed/3PZ65s2qLTE",
  152: "https://www.youtube.com/embed/SnHIS_Aqu9o",
  153: "https://www.youtube.com/embed/vUNWL4sOrd0",
  154: "https://www.youtube.com/embed/3HuTSbvyqg0",
  155: "https://www.youtube.com/embed/LO8P2NppjqU",
  156: "https://www.youtube.com/embed/2jcV7i114BQ",
  157: "https://www.youtube.com/embed/eJMIokGLsL8",
  158: "https://www.youtube.com/embed/ZYaF0zLfijg",
  159: "https://www.youtube.com/embed/WqHU2UBzQSo",
  160: "https://www.youtube.com/embed/xGRjCa49C6U",
  161: "https://www.youtube.com/embed/nO3oGPnur2Y",
  162: "https://www.youtube.com/embed/A2_yg19Pu7Y",
  163: "https://www.youtube.com/embed/GgcJmRIGspE",
  164: "https://www.youtube.com/embed/KLLVXw335u4",
  165: "https://www.youtube.com/embed/UvV-dK6Nyj8",
  166: "https://www.youtube.com/embed/nQQWVp9Ud9U",
  167: "https://www.youtube.com/embed/8yR9y8HFSSI",
  168: "https://www.youtube.com/embed/QhLMlA3Wb8w",
  169: "https://www.youtube.com/embed/_ygU_fEZ1-s",
  170: "https://www.youtube.com/embed/tBulYcyAL7o",
  171: "https://www.youtube.com/embed/jHjHu5LOyAk",
  172: "https://www.youtube.com/embed/2KGtXzIb8l8",
}
